services:
  cafesepproject:
    build: .
    container_name: cafesepproject
    ports:
      - "8001:80"
      
    environment:
      - DJANGO_SETTINGS_MODULE=projectCafeeSEP.settings
    restart: always
